/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "storage.h"


void
fildistributor_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char *registeruser_1_user;
	enum clnt_stat retval_2;
	int result_2;
	char *unregisteruser_1_user;
	enum clnt_stat retval_3;
	int result_3;
	char *connectuser_1_user;
	char *connectuser_1_ip;
	int connectuser_1_port;
	enum clnt_stat retval_4;
	int result_4;
	char *disconnectuser_1_user;
	enum clnt_stat retval_5;
	int result_5;
	char *publishfile_1_user;
	char *publishfile_1_file;
	char *publishfile_1_description;
	enum clnt_stat retval_6;
	int result_6;
	char *deletefile_1_user;
	char *deletefile_1_file;
	enum clnt_stat retval_7;
	mchains result_7;
	char *listuser_1_user;
	enum clnt_stat retval_8;
	mchains result_8;
	char *listcontent_1_user;
	char *listcontent_1_puser;
	enum clnt_stat retval_9;
	int result_9;
	char *comprobar_1_user;

#ifndef	DEBUG
	clnt = clnt_create (host, fildistributor, distrver, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = registeruser_1(registeruser_1_user, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = unregisteruser_1(unregisteruser_1_user, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = connectuser_1(connectuser_1_user, connectuser_1_ip, connectuser_1_port, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = disconnectuser_1(disconnectuser_1_user, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = publishfile_1(publishfile_1_user, publishfile_1_file, publishfile_1_description, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = deletefile_1(deletefile_1_user, deletefile_1_file, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = listuser_1(listuser_1_user, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_8 = listcontent_1(listcontent_1_user, listcontent_1_puser, &result_8, clnt);
	if (retval_8 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_9 = comprobar_1(comprobar_1_user, &result_9, clnt);
	if (retval_9 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fildistributor_1 (host);
exit (0);
}
