/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "storage.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
registeruser_1(char *user, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, registerUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unregisteruser_1(char *user, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, unregisterUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
connectuser_1(char *user, char *ip, int port, int *clnt_res,  CLIENT *clnt)
{
	connectuser_1_argument arg;
	arg.user = user;
	arg.ip = ip;
	arg.port = port;
	return (clnt_call (clnt, connectUser, (xdrproc_t) xdr_connectuser_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
disconnectuser_1(char *user, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, disconnectUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
publishfile_1(char *user, char *file, char *description, int *clnt_res,  CLIENT *clnt)
{
	publishfile_1_argument arg;
	arg.user = user;
	arg.file = file;
	arg.description = description;
	return (clnt_call (clnt, publishFile, (xdrproc_t) xdr_publishfile_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
deletefile_1(char *user, char *file, int *clnt_res,  CLIENT *clnt)
{
	deletefile_1_argument arg;
	arg.user = user;
	arg.file = file;
	return (clnt_call (clnt, deleteFile, (xdrproc_t) xdr_deletefile_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
listuser_1(char *user, mchains *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, listUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_mchains, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
listcontent_1(char *user, char *puser, mchains *clnt_res,  CLIENT *clnt)
{
	listcontent_1_argument arg;
	arg.user = user;
	arg.puser = puser;
	return (clnt_call (clnt, listContent, (xdrproc_t) xdr_listcontent_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mchains, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
comprobar_1(char *user, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, comprobar,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
