/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include "../operations.h"

bool_t
registeruser_1_svc(char *user, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	registerUser(user);
	retval = TRUE;
	return retval;
}

bool_t
unregisteruser_1_svc(char *user, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	unregisterUser(user);
	retval = TRUE;
	return retval;
}

bool_t
connectuser_1_svc(char *user, char *ip, int port, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	connectUser(user, ip, port);
	retval = TRUE;
	return retval;
}

bool_t
disconnectuser_1_svc(char *user, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	disconnectUser(user);
	retval = TRUE;
	return retval;
}

bool_t
publishfile_1_svc(char *user, char *file, char *description, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	publishFile(user, file, description);
	retval = TRUE;
	return retval;
}

bool_t
deletefile_1_svc(char *user, char *file, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	deleteFile(user, file);
	retval = TRUE;
	return retval;
}

bool_t
listuser_1_svc(char *user, mchains *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	list_users(user);
	retval = TRUE;
	return retval;
}

bool_t
listcontent_1_svc(char *user, char *puser, mchains *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	list_content(user, puser);
	retval = TRUE;
	return retval;
}

bool_t
comprobar_1_svc(char *user, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	check_User(user);
	retval = TRUE;
	return retval;
}

int
fildistributor_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
