/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include "../operations.h"

bool_t
startserver_1_svc(void *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	startServer();

	return retval;
}

bool_t
stopserver_1_svc(void *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	stopServer();
	return retval;
}

bool_t
registeruser_1_svc(char *user, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	registerUser(*user);
	return retval;
}

bool_t
unregisteruser_1_svc(char *user, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	unregisterUser(*user);
	return retval;
}

bool_t
connectuser_1_svc(char *user, char *ip, int port, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	int connectUser(char *user, char *ip, int port);
	return retval;
}

bool_t
disconnectuser_1_svc(char *user, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	int disconnectUser(char *user);
	return retval;
}

bool_t
publishfile_1_svc(char *user, char *file, char *description, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	int publishFile(char *user, char *file, char *description);
	return retval;
}

bool_t
deletefile_1_svc(char *user, char *file, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	int deleteFile(char *user, char *file);
	return retval;
}

bool_t
listoneuser_1_svc(int usernumber, chain *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
listonecontent_1_svc(int one, chain *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
comprobar_1_svc(char *user, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	check_User(*user);

	return retval;
}

int
fildistributor_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
