/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_chain (XDR *xdrs, chain *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->res, 1024))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_connectuser_1_argument (XDR *xdrs, connectuser_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->user, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ip, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_publishfile_1_argument (XDR *xdrs, publishfile_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->user, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->description, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_deletefile_1_argument (XDR *xdrs, deletefile_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->user, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file, ~0))
		 return FALSE;
	return TRUE;
}
