void startServer();
void stopServer();
int registerU(char *localUser);
int unregisterU(char *localUser);
int connectU(char *localUser, char *ip, int port);
int disconnectU(char *user);
int publishF(char *user, char *file, char *description);
int deleteF(char *user, char *file);
int list_users(char *user, char *** list);
int check_User(char *user);
int list_content(char *user, char *sourceUser, char *** list);
